### ISSUE TITLE
Check communication with Elastic APM Server

### ISSUE THREAD

**Issue by victorpintot8** [arkaitzgarro/elastic-apm-laravel#137]
Hi!, is there any method to check the coomunication between the agent and the apm server?, I'm trying to debug the installation. I did follow all the steps but's not working on Lumen 8.1, it does work on Laravel.

**Comment by arkaitzgarro** [comment]
Hi @victorpintot8,

Unfortunately, this package is not compatible with Lumen, only with Laravel. I don't have experience when Lumen, but I've just installed the package in a fresh project, and it crashes because some application events are not available, and I expect more things to fail to be honest. The part you are probably missing to "make it work" is to register the service provider in your `bootstrap.php` file.

```php
$app->register(\AG\ElasticApmLaravel\ServiceProvider::class);
```

Happy to accept PRs to make this project compatible with Lumen though :)
