### ISSUE TITLE
Issue with Octane

### ISSUE THREAD

**Issue by afiqiqmal** [arkaitzgarro/elastic-apm-laravel#145]
There is an issue when running with Octane

Here is the error

```
Undefined constant "AG\ElasticApmLaravel\Collectors\LARAVEL_START"
```

**Comment by arkaitzgarro** [comment]
Hi @afiqiqmal,

I'm not familiar with Octane, but since it keeps the application running in memory, I'm guessing that the [`index.php` ](https://github.com/laravel/laravel/blob/8.x/public/index.php#L6) file is not executed anymore, and thus the variable `LARAVEL_START` is never defined.

It seems to be possible to add a listener for `RequestReceived` event in [Octane configuration](https://github.com/laravel/octane/blob/1.x/config/octane.php#L69). Could you try to add your own listener and add `define('LARAVEL_START', microtime(true));` so the constant gets initialized on every request?
