### ISSUE TITLE
Jobs not tracked

### ISSUE THREAD

**Issue by tomvo** [arkaitzgarro/elastic-apm-laravel#169]
Hi,

I'm running APM + this package on one of our job servers. The server runs an install of our application with Laravel Horizon. 
The only thing i'm seeing tracked in APM are the Artisan commands. I'm not seeing any Job execution. 

![image](https://user-images.githubusercontent.com/1503385/183354117-61dc9704-6be1-4daf-8c8d-85f99962435b.png)

Also, i'm not seeing any exceptions either.

Any idea what i'm missing?

Best,
Tom

**Comment by countless-integers** [comment]
Are those workers picking up code changes you're deploying?

Does the `job` category even appear in the UI for you? 

![Screenshot 2022-08-11 at 10 01 47](https://user-images.githubusercontent.com/2060726/184089748-77c193f9-0e59-420f-ae4a-1c84a4e4561e.png)

**Comment by tomvo** [comment]
@countless-integers thanks for your reply Adrian. So the code is picked up by the workers because it is logging the artisan commands executed by the same environment. I confirmed this also by changing the app name of the jobs server. And I do see this app name show up in transactions. But as said only with the artisan commands. 

I do not see the jobs value in the dropdown. 

Any other clues as to what I could try?

**Comment by countless-integers** [comment]
The reason I asked about that is because usually workers run as continuous processes, so they need to be reloaded to pick up any code changes -- ofc it all depends on what your setup is. 

No clue unfortunately.

**Comment by dstepe** [comment]
Sorry I'm a little late to the party. I confirmed that we are seeing APM data for jobs executed on our jobs server, but our environment is certainly different (we don't use Horizon for example). For jobs, the data is sent to APM as a result of listening for the `JobProcessed` event. (See [the collector](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/baaa1d347d4588ea5ddc4834ff50637a4ab29ccf/src/Collectors/JobCollector.php#L46) for details.) Could something in your application either cause that event to not fire or otherwise disrupt the logic required for the send to be executed?

**Comment by tomvo** [comment]
Hi all, sorry for my late reply but I reached out to Elastic Support and they told me that since some time the APM php package supports Laravel out of the box. At the moment i'm not sure if I should use this package on top of the APM install or not? Any feedback would be appreciated!

**Comment by dstepe** [comment]
The [APM Agent for PHP](https://github.com/elastic/apm-agent-php) is an extension which you must install in our PHP runtime. This package and the underlying APM Agent predate the creation of the official extension and their interoperability is unknown. However, since the two implementations have no actual awareness of each other, I think only one should be used, otherwise you will send duplicate transaction data.

**Comment by arkaitzgarro** [comment]
Hey @tomvo, thanks for the info. As @dstepe mentioned, the official APM agent is installed directly in the server as a PHP runtime extension, and not as a Laravel dependency. I didn't try it yet, but if you have the chance and can/want to share your impression here, you are more than welcome.

**Comment by tomvo** [comment]
hey @arkaitzgarro sorry for bumping on this closed issue. I just got another reply from Elastic on my question on how to differentiate between environments. They mentioned:

> I was checking internally, and it seems it is only possible to do such environment separation having different php.ini files.

So for anyone else stumbling upon this, please know this. This means i'll probably switch to using this package instead of the PHP Agent.
